#!/usr/bin/env python
"""Generate config/tooltips.yaml from compact specs. Every entry carries all required fields (Section 12)."""
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

# (key, label, short, how calculated, where it comes from, how to read, why the NSW cares, caveats, needs)
S = [
 # ---- money flow
 ("assessed", "Assessed", "Total fees and duties the agencies have charged on consignments in the selected period.", "Sum of fee assessments (in naira) raised in the period that match the filters; foreign-currency fees use the exchange rate on the assessment day.", "fee_assessments", "Compare with Paid to see what is still outstanding; a persistent gap signals unpaid or delayed payments.", "It is the starting point of the reconciliation chain: if assessment is wrong everything downstream is wrong.", "Synthetic NSW-channel data only, not total agency revenue.", "trust"),
 ("paid", "Paid", "Money confirmed as received against assessed fees in the period.", "Sum of payment allocations whose payment was confirmed in the period; each allocation ties a payment to one assessment.", "payments, payment_allocations", "Paid should track Assessed with a lag of a day or two; foreign-currency fees can differ slightly because payers pay at the payment-day rate.", "It shows how quickly traders fund their assessments through the single window.", "Duplicate and unmatched payments are excluded; they appear as exceptions.", "trust"),
 ("settled", "Settled", "Net amount released from the collection account to agencies after collection costs.", "Sum of settled allocation amounts (paid minus collection cost) whose settlement batch completed in the period.", "payment_allocations, settlements, settlement_batches", "Settled trails Paid by the bank settlement lag (about one day); a growing gap means money is held up at a bank.", "Agencies only see cash when settlement completes, so lag directly affects their operations.", "Net of collection costs; gross settled is shown on the reconciliation page.", "trust"),
 ("remitted", "Remitted", "Amounts agencies have paid on to the Treasury (Federation Account) in the period.", "Sum of remittances paid in the period, per each agency's simulated remittance rule (monthly or quarterly share).", "remittances", "Remittances follow settlements by weeks; compare the due date with the paid date to see punctuality.", "Timely remittance protects government cash flow.", "Remittance rules are simulated approximations.", "supervision"),
 ("outstanding", "Outstanding", "Assessed amounts not yet paid.", "Assessed minus paid, per assessment, summed over assessments raised in the period.", "fee_assessments, payment_allocations", "A small figure that is mostly recent assessments is normal; old unpaid items are exceptions.", "It shows revenue at risk of leakage.", "Recent assessments are timing items, not errors; ageing shows the difference.", "trust"),
 ("in_transit", "In transit", "Money paid by traders but not yet settled to the agencies.", "Sum of payment allocations in the period that have no completed settlement as of the data time.", "payment_allocations", "Normal values are about one day of collections; larger values point to a slow bank.", "It is the float the settlement rail is holding.", "Timing item, not an error, until it is older than two days.", "trust"),
 ("collection_efficiency", "Collection efficiency", "Share of assessed value that has reached the agencies as settled cash.", "Settled gross divided by assessed for the same set of assessments.", "fee_assessments, payment_allocations", "Close to 100% for mature periods; recent periods are lower because of timing.", "A single, simple measure of how much of what was charged was actually collected.", "Depends on how old the assessments are.", "trust"),
 ("cost_of_collection", "Cost of collection", "What it costs to collect the money: fees withheld at settlement.", "Sum of collection costs withheld on settled allocations (rate set per agency profile).", "settlements", "Compare across agencies and over time; spikes are flagged by rule R-CASH-01.", "Lower collection cost leaves more for government.", "Simulated rates; does not include agencies' own operating costs.", "trust"),
 ("collection_cost_per_100", "Cost of collection per ₦100", "Collection costs for every ₦100 collected.", "100 x collection cost divided by gross settled amount.", "settlements", "Typically well below ₦1; compare agencies.", "Efficiency of the collection channel in one number.", "Simulated.", "trust"),
 ("refunds", "Refunds", "Fees returned or adjusted after assessment.", "Sum of fee refunds posted in the period (refunds of unapplied receipts are balance-sheet only).", "refunds", "Small and steady is normal.", "Large refunds suggest assessment errors.", "Synthetic adjustments.", "trust"),
 ("fx_effect", "FX effect", "Change in naira collections caused by exchange-rate movement on foreign-currency fees.", "Foreign-currency fee amounts multiplied by the day's USD/NGN rate versus a constant rate; realised differences post to FX gains and losses.", "fee_assessments, fx_rates, journal_lines", "A weaker naira raises naira value of USD fees.", "Shows how currency moves change agency income.", "FX path is simulated within configured bounds.", "trust"),
 ("funds_in_transit", "Funds in transit", "Ledger account holding paid money until settlement.", "Account 1105: debits on payment confirmation, credits on settlement.", "journal_lines", "Balance approximates in-transit money.", "Ties payments to settlements in the ledger.", "Balances per entity.", "trust"),
 ("remittance_payable", "Remittance payable", "Amount an agency owes the Treasury but has not yet paid.", "Account 2300: credited when the obligation is recognised at period end, debited when paid.", "journal_lines, remittances", "Rises at month end and falls on payment.", "Shows liabilities to the Treasury.", "Simulated rules.", "supervision"),
 ("distribution_to_treasury", "Distribution to Treasury", "Recognised share of income owed to the Treasury.", "Account 3200: debited when the remittance obligation arises.", "journal_lines", "Compare with remittances paid.", "Separates what is owed from what is paid.", "Equity account.", "supervision"),
 ("appropriation", "Appropriation", "Government budget releases funding an agency's operations.", "Sum of appropriation receipts (account 4800).", "funding_receipts", "Regular releases cover part of operating cost.", "Shows how operations are funded alongside fee income.", "Synthetic.", "trust"),
 ("partner_grants", "Partner grants", "Funding from partner facilities, tagged by partner country.", "Sum of grant and concessional-loan receipts, grouped by partner country.", "funding_receipts", "Quarterly lumps are normal.", "Shows which partner countries support which agencies.", "Facility names are generic and simulated.", "trust"),
 # ---- reconciliation
 ("four_way_match", "Four-way match", "Checks each charge from assessment to payment to settlement to remittance and flags where money stops.", "For each fee assessment we link its payment allocation, settlement and remittance share and compute the difference at each step; differences are classified.", "fee_assessments, payment_allocations, settlements, remittances", "Each step should be no larger than the one before, apart from timing; large drops show where to investigate.", "It turns 'do the numbers agree?' into a precise, auditable list of exceptions.", "Timing differences are shown as in transit, not errors.", "trust, supervision"),
 ("variance", "Variance", "Difference between two steps of the reconciliation chain.", "Amount at one step minus amount at the next, for the same assessments.", "reconciliation chain", "Explained variances are timing or rule-based; unexplained ones are exceptions.", "It pinpoints where money is delayed or lost.", "Computed on the filtered cohort.", "trust"),
 ("unpaid", "Unpaid", "Assessments older than 72 hours with no payment.", "Assessed amount where paid is zero and age exceeds 72 hours.", "v_assessed_vs_paid", "Few and recent is normal.", "Unpaid items are potential leakage.", "Synthetic.", "trust"),
 ("part_paid", "Part paid", "Assessments paid for less than the assessed naira amount.", "Paid below 99.5% of assessed for naira-denominated fees.", "v_assessed_vs_paid", "Should be rare.", "Part payments hold cargo.", "FX-denominated fees are tolerated within 5%.", "trust"),
 ("overpaid", "Overpaid", "Assessments paid for more than the assessed naira amount.", "Paid above 100.5% of assessed for naira-denominated fees.", "v_assessed_vs_paid", "Should be rare.", "Overpayments create refund work.", "FX differences are not counted.", "trust"),
 ("duplicate_payment", "Duplicate payment", "A second payment with the same payer and amount for the same consignment.", "Payments flagged as duplicates that have not yet been refunded.", "payments", "Bursts raise rule R-DUP-01.", "Duplicates tie up trader money and need refunds.", "Synthetic.", "trust"),
 ("orphan_payment", "Orphan payment", "A payment that matches no open assessment.", "Confirmed payments whose reference is unmatched and not yet refunded.", "payments", "Usually mistyped references.", "Needs manual matching or refund.", "Synthetic.", "trust"),
 ("assessment_mismatch", "Assessment mismatch", "Assessed amount differs from the fee-rule expectation by more than 1%.", "Absolute difference between assessed and expected exceeds 1% of expected.", "fee_assessments", "Small random differences are valuation adjustments.", "Systematic mismatches signal under-assessment.", "Expected amount comes from the simulated fee rules.", "trust"),
 ("leakage_indicator", "Leakage indicator", "Where assessed amounts fall short of what the fee rule expects, by commodity and origin.", "(Expected minus assessed) divided by expected, for each commodity and origin pair with enough assessments.", "fee_assessments", "Red cells above 8% over three days raise rule R-FEE-01.", "It is the revenue-assurance early warning.", "Needs at least 15 assessments per cell.", "trust"),
 ("expected_amount", "Expected amount", "What the fee rule says should be charged for the consignment.", "Fee rule applied to the consignment's value, weight, mode and origin (including country sensitivity and FX).", "fee_assessments", "Compare with assessed.", "Gives a neutral benchmark for assessment accuracy.", "Rules are simulated.", "trust"),
 # ---- speed
 ("dwell_time", "Dwell time", "Days a consignment spends in Nigeria's trade chain from vessel or flight arrival until it leaves the port or airport gate.", "gate_out_at minus arrived_at per consignment, then median and percentiles over consignments that left in the period.", "consignments, stage_events", "Compare with the published baseline (18-21 days), the target (under 7 days by end 2026) and peers; split into digital and physical stages.", "It is the public yardstick of the programme and drives demurrage and trader cost.", "Synthetic data. Clearance time is shorter (declaration to release).", "speed"),
 ("clearance_time", "Clearance time", "Days from declaration filed to customs release.", "released_at minus declared_at per consignment.", "consignments", "Shorter than dwell time.", "Measures the customs and agency part of the journey.", "Synthetic.", "speed"),
 ("release_to_exit", "Release to exit", "Days from customs release to gate-out.", "gate_out_at minus released_at.", "consignments", "Dominated by terminal and haulage.", "Shows delay after customs has finished.", "Synthetic.", "speed"),
 ("stage_wait", "Stage wait", "Time a consignment waits before an agency or operator starts a stage.", "started_at minus ready_at for a stage, in hours.", "stage_events", "Long waits mean queues.", "Waiting, not processing, is most of the delay.", "Waits are sampled by the simulation.", "speed"),
 ("handoff_wait", "Hand-off wait", "Time lost between one party finishing and the next starting.", "Median wait before each stage.", "stage_events", "Large values show coordination gaps.", "Hand-off accountability across agencies.", "Synthetic.", "speed"),
 ("p50", "Median (p50)", "The middle value: half of consignments are faster, half slower.", "50th percentile of the metric.", "consignments", "Use with p90 to see predictability.", "Typical experience of a trader.", "Percentiles use completed consignments only.", "speed"),
 ("p90", "p90", "Nine in ten consignments are faster than this.", "90th percentile of the metric.", "consignments", "A big gap to the median means unpredictable clearance.", "Predictability matters as much as the average.", "Completed consignments only.", "speed"),
 ("sla_breach_rate", "SLA breach rate", "Share of stage records that took longer than the service level.", "Records with processing time above the stage SLA divided by all records with an SLA.", "stage_events", "Under 15% is healthy; above raises R-SLA-01.", "Measures agency timeliness.", "SLA hours are simulated.", "speed, supervision"),
 ("digital_vs_physical", "Digital vs physical time", "Splits delay into stages the NSW platform controls (digital) and stages it does not (scanners, terminals, trucks).", "Sum of stage waits and durations by system type, as a share of total time per consignment.", "consignments, stage_events", "If the digital share falls while total time stays high, physical constraints dominate.", "Shows progress the platform can claim and bottlenecks outside its control.", "Stage boundaries are simulated.", "speed, trust"),
 ("risk_lane", "Risk lane", "Customs risk-based channel: green, yellow, red or blue.", "Assigned at manifest from origin risk and commodity risk probabilities.", "consignments", "Red lanes need physical examination.", "Lane mix drives examination workload.", "Probabilities are simulated.", "speed"),
 ("scanner_utilisation", "Scanner status", "How many scanners are working at each port.", "Total scanners minus those offline (beats and injected incidents).", "incidents", "Fewer working scanners lengthen exam waits.", "Physical capacity limits clearance speed.", "Simulated capacity.", "speed"),
 ("target_tracker", "Target tracker", "Weekly median dwell against the published baseline, target and peers.", "Median dwell by gate-out week with a trend projection.", "consignments", "A falling line approaching the target is progress.", "Lets leaders prove progress towards the end-2026 goal.", "Published figures: verify before quoting.", "speed"),
 ("projection_method", "Projection method", "How the date to reach the target is estimated.", "Least-squares line through the last eight complete weekly medians, extrapolated; 95% band from residual error.", "weekly medians", "Treat as a guide, not a forecast.", "Gives a reproducible, transparent estimate.", "Assumes the recent pace continues; ignores seasonality and incidents.", "speed"),
 ("cost_of_delay", "Cost of delay", "Illustrative cost of dwell beyond a reference number of days.", "Excess days times demurrage per TEU-day, storage per tonne-day and inventory carrying cost on cargo value.", "consignments (assumptions editable)", "Use to size the benefit of faster clearance.", "Puts a money value on delay.", "Assumptions are illustrative and editable.", "speed"),
 ("peer_benchmarks", "Peer benchmarks", "Published clearance times of comparable ports and countries.", "Reference values (Ghana 5-7 days, Benin about 4, global about 4, Rwanda about 1.5).", "published figures", "Shows the gap to leaders.", "Gives context for the target.", "Published figure, verify before quoting.", "speed"),
 # ---- trust
 ("data_confidence_score", "Data confidence score", "A 0-100 score of how complete, timely and consistent an agency's data is.", "40% completeness, 25% timeliness, 20% consistency, 15% remittance punctuality (weights configurable).", "stage_events, fee_assessments, remittances", "Above 90 is healthy; 75-90 needs attention; below 75 treat figures with caution.", "Leaders see how far to trust each number.", "Weights are illustrative.", "trust, supervision"),
 ("ties_out_check", "Ties out", "Confirms a line equals the sum of what is behind it at every level.", "Line total compared with the sum of accounts, journal entries and source documents.", "journal_lines, source tables", "Green means exact agreement to the kobo.", "Proves figures are traceable.", "Checked for each level shown.", "trust"),
 ("report_fingerprint", "Report fingerprint", "A code that identifies exactly what a report contained.", "SHA-256 of the report parameters, as-of time, row counts and totals.", "report", "Same inputs at the same as-of give the same fingerprint.", "Lets anyone reproduce a number later.", "Changes if any input changes.", "trust"),
 ("as_of", "As of", "The moment in time the numbers describe.", "Only facts that occurred at or before this time are included.", "all tables", "Live views use the current simulated time.", "Prevents future data leaking into past reports.", "Times shown in WAT.", "trust"),
 ("ledger_trial_balance", "Trial balance", "All accounts with debit and credit totals; they must balance.", "Sum of journal line debits and credits by account up to the date.", "journal_lines", "Debits equal credits.", "A basic integrity test of the ledger.", "Per entity or consolidated.", "trust"),
 ("journal_entry", "Journal entry", "One balanced accounting posting linked to a source document.", "Debit and credit lines with equal totals, tagged with origin country and process.", "journal_entries, journal_lines", "Open the entry to see its source documents.", "Every figure rests on entries like this.", "Synthetic.", "trust"),
 ("trace_levels", "Trace levels", "The path from a statement line down to a consignment.", "L0 line, L1 accounts, L2 journal entries, L3 source documents, L4 consignment.", "ledger and source tables", "Totals at each level sum to the level above.", "Shows any number can be defended.", "Entries are paged.", "trust"),
 ("verified_answer_badge", "Verified badge", "Shows whether every number in an assistant answer came from a tool.", "Numbers in the answer are matched to tool outputs within 0.5%.", "assistant tool results", "Verified means all numbers matched; partial lists the unmatched ones.", "Builds trust in conversational answers.", "Rounded values are matched within tolerance.", "trust"),
 ("synthetic_data", "Synthetic data", "All data in this demo is invented.", "Generated by a simulation guided by a language model and checked by code.", "simulation", "Never quote as real agency performance.", "Avoids any implication about real agencies.", "Fee names, rates and IDs are simulated.", "trust"),
 # ---- supervision
 ("alert_severity", "Alert severity", "How urgent an alert is: info, low, medium or high.", "Set by the rule definition.", "alerts", "High alerts need attention first.", "Helps supervisors prioritise.", "Thresholds are configurable.", "supervision"),
 ("review_states", "Review states", "Open, acknowledged, under review, resolved or dismissed.", "Moves forward through role-permitted actions; every move is logged.", "reviews, audit_log", "Open items age until acted on.", "Accountability for each alert.", "Demo roles, no real login.", "supervision"),
 ("roles", "Roles", "Analyst, Supervisor and Director with different permissions.", "Analyst acknowledges and comments; Supervisor assigns and resolves; Director signs off reports.", "reviews", "Switch roles in the sidebar.", "Shows segregation of duties.", "No real authentication in the demo.", "supervision"),
 ("onboarding_score", "Onboarding score", "How much of an agency's activity arrives digitally.", "Share of stage records captured digitally rather than manually.", "stage_events", "Below 80% raises R-ONB-01.", "Tracks agency adoption.", "Simulated improvement path.", "supervision"),
 ("remittance_lateness", "Remittance lateness", "Days after the due date that a remittance was paid, or has been outstanding.", "Paid date minus due date; unpaid items are measured to now.", "remittances", "More than 3 days raises R-REM-01.", "Timely remittance protects Treasury cash flow.", "Simulated due dates.", "supervision"),
 ("settlement_lag", "Settlement lag", "Hours from a bank's daily batch closing to its completion.", "Completed minus closed time per batch.", "settlement_batches", "About one day is normal; more than 48 hours raises R-SET-01.", "Slow banks hold agency cash.", "Simulated bank lags.", "supervision"),
 ("audit_log", "Audit log", "A permanent record of every action and system alert.", "Rows are appended for each review action, sign-off and alert raised.", "audit_log", "Read from newest to oldest.", "Supports accountability and investigation.", "Demo log.", "supervision"),
 # ---- country / process
 ("origin_country", "Origin country", "Country the cargo comes from (or that supplies the funds).", "Tag on each consignment, assessment, payment and ledger line.", "consignments", "Compare countries by value and fee yield.", "Policy and risk differ by origin.", "Twenty origin countries are modelled.", "trust"),
 ("country_sensitivity", "Country sensitivity", "How an agency's fees, inspections and delays vary by origin country.", "Per agency and country: fee multiplier, inspection modifier, document-issue rate and dwell modifier.", "entity profiles", "Values near 1 are neutral.", "Explains differences between origins.", "Generated within bounds.", "trust"),
 ("process_code", "Process", "The agency process that a fee belongs to (for example valuation or wharfage).", "Process code on the fee rule.", "fee_assessments", "Group by process to see yield.", "Links money to the work that earns it.", "Process names are simulated.", "trust"),
 ("fee_code", "Fee code", "Identifier of a fee type (for example NCS-DUTY).", "Defined in each agency profile.", "fee_assessments", "One revenue account per fee.", "Lets statements trace to fee types.", "Simulated names.", "trust"),
 ("commodity_group", "Commodity group", "Ten broad groups of goods that drive duty, permits and inspections.", "Assigned to each consignment from its HS code.", "consignments", "Compare groups.", "Policy and permits differ by commodity.", "Simulated mapping.", "trust"),
 ("hs_code", "HS code", "Harmonised System code classifying the goods (8 digits with dots).", "Chosen from the commodity group's list.", "consignments", "Used for duty and permits.", "Classification drives revenue.", "Simulated.", "trust"),
 ("partner_country", "Partner country", "Country of the partner facility funding an agency.", "Tag on grant and concessional-loan receipts.", "funding_receipts", "Compare by partner.", "Shows external support.", "Generic facility names.", "trust"),
 # ---- live
 ("live_feed", "Live feed", "Real-time operational events from the Single Window.", "Events written by the engine, rules and the model; newest first.", "live_events", "Click a reference to trace it.", "Shows the channel is live and observable.", "Backfilled history is sampled.", "speed"),
 ("events_per_minute", "Events per minute", "How busy the feed is.", "Count of events in each minute.", "live_events", "Spikes follow incidents.", "Activity level at a glance.", "Synthetic rate.", "speed"),
 ("live_speed", "Live speed", "Time-lapse factor for the live simulation.", "The simulated clock advances at this multiple of real time (capped).", "service", "1 is real time.", "Makes short demos busier.", "Every live event is flagged with the factor.", "speed"),
 ("degraded_mode", "Degraded mode", "The language model is unavailable or over budget; deterministic fallback keeps running.", "Status set after repeated model failures or when the token budget is reached.", "llm status", "Banner shows the reason.", "The demo never freezes.", "Content falls back to templates.", "trust"),
 ("directive", "Directive", "A bounded adjustment the director gives the engine for the next window.", "Arrival multiplier, scanner status, permit pressure, settlement lag and payment failure rate within allowed ranges.", "directives", "Small changes unless an incident is active.", "Shows how the model shapes live conditions.", "Engine enforces bounds.", "speed"),
 # ---- filters
 ("filter_period", "Period", "Time range for every page that can use it.", "Presets or a custom range, in WAT.", "filters", "Use Compare to see the previous period.", "Consistent period across pages.", "Some pages ignore it (stated on the page).", "trust"),
 ("compare_previous_period", "Compare to previous period", "Adds a column comparing with the equal-length period before.", "Same calculation for the preceding period.", "filters", "Positive deltas mean growth.", "Shows direction at a glance.", "Needs a start date.", "trust"),
 ("filter_entities", "Entities", "Agencies to include.", "Filters by entity on every query that has an entity.", "filters", "Leave empty for all.", "Focus on one agency.", "Some measures have no entity.", "trust"),
 ("filter_origin", "Origin country", "Countries of origin to include.", "Filters consignments, assessments, payments and ledger lines.", "filters", "Leave empty for all.", "Compare origins.", "Not applicable to expenses.", "trust"),
 ("filter_mode", "Mode", "Sea or air.", "Filters by transport mode.", "filters", "Leave empty for both.", "Sea and air behave differently.", "Not applicable to some ledger views.", "trust"),
 ("filter_port", "Port / airport", "Specific ports or airports.", "Filters by port code.", "filters", "Apapa and Tin Can carry most sea volume.", "Locate bottlenecks.", "Not applicable to ledger.", "trust"),
 ("filter_commodity", "Commodity group", "Goods groups to include.", "Filters by commodity group.", "filters", "Leave empty for all.", "Commodity drives permits.", "Not applicable to expenses.", "trust"),
 ("filter_process", "Process / fee type", "Agency process or fee code.", "Filters fee assessments and payments by process or fee.", "filters", "Leave empty for all.", "Link money to work.", "Not applicable to consignment counts.", "trust"),
 ("currency_view", "Currency view", "Show amounts in naira or US dollars.", "Dollar view divides each transaction by that day's USD/NGN rate.", "fx_rates", "Dollar view removes exchange-rate effects.", "Context for foreign partners.", "Simulated rates.", "trust"),
 ("filter_severity", "Severity", "Alert severities to show.", "Filters alerts.", "filters", "Start with high.", "Prioritisation.", "Only on alert views.", "supervision"),
 ("filter_status", "Status", "Alert or review status.", "Filters alerts by state.", "filters", "Open items first.", "Work queue.", "Only on alert views.", "supervision"),
 ("export_pdf", "Export PDF", "Download the report as a watermarked PDF.", "Rendered from the computed report with the disclaimer on every page.", "report", "Print or share.", "Board-ready output.", "Tables are truncated for length.", "trust"),
 ("export_excel", "Export Excel", "Download one sheet per section plus metadata.", "Written from the computed report; disclaimer on each sheet.", "report", "Open in Excel.", "Analysis outside the app.", "Synthetic.", "trust"),
 ("export_csv", "Export CSV bundle", "Download every table as CSV in one zip.", "Each report table written as a file with the disclaimer.", "report", "Use in other tools.", "Open data format.", "Synthetic.", "trust"),
 ("export_html", "Export HTML", "Download a self-contained web page of the report.", "Rendered with the disclaimer and watermark.", "report", "Open in any browser.", "Easy sharing.", "Synthetic.", "trust"),
 # ---- scorecard components, page helpers
 ("score_completeness", "Completeness", "Share of an agency's stage records that have all fields.", "Records with a start time divided by all records, last seven days.", "stage_events", "Drops show data gaps.", "40% of the confidence score.", "Fee-only agencies default to 100%.", "trust"),
 ("score_timeliness", "Timeliness", "Share of records processed within the service level.", "One minus the SLA breach rate, last seven days.", "stage_events", "Higher is better.", "25% of the confidence score.", "Agencies with no SLA stages default to 100%.", "supervision"),
 ("score_consistency", "Consistency", "Whether assessments tie to payments, settlements and the fee rule.", "Half the share fully paid and settled, half the share within 1% of expected.", "fee_assessments", "Higher is better.", "20% of the confidence score.", "Uses assessments 3 to 14 days old.", "trust"),
 ("score_punctuality", "Remittance punctuality", "Share of remittances paid within a day of the due date.", "Remittances paid with at most one day late, last 120 days.", "remittances", "Higher is better.", "15% of the confidence score.", "Few remittances per period.", "supervision"),
 ("entity_tile", "Entity tile", "Collections, status and trend for one agency.", "Assessed in the period, RAG from the scorecard, sparkline of daily paid.", "scorecard", "Click to open the Entity Explorer.", "Portfolio view of agencies.", "RAG is illustrative.", "supervision"),
 ("kpi_open_alerts", "Open high alerts", "High-severity alerts not yet resolved.", "Count of alerts with high severity and an open state.", "alerts", "Aim for zero.", "Immediate supervision workload.", "As of the data time.", "supervision"),
 ("kpi_consignments", "Consignments", "Consignments manifested in the period.", "Count of consignments with manifest time in the period.", "consignments", "Seasonality and holidays move it.", "Volume context.", "Synthetic.", "speed"),
 ("situation_board", "Situation board", "Active incidents, scanners, permit queues and settlement lags.", "Engine incidents plus recent queue and lag statistics.", "incidents, stage_events, settlement_batches", "Red items need attention.", "One-glance operational picture.", "Simulated.", "supervision"),
 ("country_map", "Collections by origin country", "Map of assessed fees by origin country.", "Sum of assessed amounts grouped by origin country.", "fee_assessments", "Darker is larger.", "Where the money comes from.", "Simulated origin mix.", "trust"),
 ("stage_waterfall", "Stage waterfall", "Median hours per stage, split digital and physical.", "Median of wait plus duration per stage for the period.", "stage_events", "Tall physical bars are the last mile.", "Shows where time is lost.", "Medians do not add to the median dwell.", "speed"),
 ("bottleneck_finder", "Bottleneck finder", "Stages ranked by their contribution to delay.", "Mean hours per consignment by stage (slowest permit agency for permits).", "stage_events", "Top items first; check whether the NSW controls them.", "Focuses investment.", "Based on completed consignments.", "speed"),
 ("exceptions_table", "Exceptions", "Items that break the four-way match.", "Rows classified as unpaid, settled late, duplicate, orphan, mismatch, part-paid or overpaid.", "reconciliation", "Select a row to trace or raise a review.", "Turns discrepancies into work items.", "Timing items are excluded.", "trust, supervision"),
 ("ageing", "Unpaid ageing", "Unpaid assessments by age bucket.", "Open amount grouped by days since assessment.", "v_assessed_vs_paid", "Older buckets are riskier.", "Prioritises collection.", "Synthetic.", "trust"),
 ("variance_bridge", "Variance bridge", "Waterfall from assessed to remitted explaining each gap.", "Unpaid, in transit, collection cost, retained share and awaiting remittance are subtracted in turn.", "reconciliation", "Each step is a named category.", "Shows exactly where money sits.", "Retained share follows the simulated rule.", "trust"),
 ("alert_board", "Alert board", "All alerts with filters and actions.", "Rows from the rules engine with their review state.", "alerts", "Open an alert to see why it was raised.", "Supervision workbench.", "Demo roles.", "supervision"),
 ("why_raised", "Why was this raised?", "The supporting rows and numbers behind an alert.", "Metric, threshold, window and the records that caused it.", "alerts", "Follow the links to trace.", "Evidence for every alert.", "First 25 rows shown.", "supervision, trust"),
 ("review_queue", "Review queue", "Work items awaiting action with age.", "Open alerts, raised exceptions and unsigned reports.", "alerts, reviews", "Oldest first.", "Keeps accountability visible.", "SLA age in hours.", "supervision"),
 ("remittance_monitor", "Remittance monitor", "Due versus paid remittances by agency.", "Due date, paid date and days late from remittances.", "remittances", "Late items are red.", "Treasury cash-flow control.", "Simulated rules.", "supervision"),
 ("report_params", "Report parameters", "Choose period, entities, sections and comparison.", "Parameters are fixed into the fingerprint.", "report", "Compute to run.", "Reproducible reports.", "Open current day included.", "trust"),
 ("report_narrative", "Narrative", "Optional executive summary written by the language model.", "The model receives computed facts only; a verifier removes any sentence with unmatched numbers.", "report", "Check the verified status.", "Plain-language summary without numeric risk.", "Needs the model to be available.", "trust"),
 ("assistant_basis", "How I computed this", "The tools and arguments used for an answer.", "Each tool call with arguments, rows returned, duration and formula.", "assistant", "Open to audit an answer.", "Transparency of conversational answers.", "Row counts are capped.", "trust"),
 ("architecture", "Architecture", "How the console plugs into the NSW.", "Read-only connections to NSW and agency systems feed a validated ledger and analytics store.", "design", "Toggle hosting to change the diagram.", "No disruption to live operations.", "Conceptual.", "trust"),
 ("admin_controls", "Admin controls", "Presenter controls for the simulation.", "Commands are queued to the service and applied on its next tick.", "service", "Use with presenter mode.", "Drive the live demo.", "Injected incidents are real engine inputs.", "supervision"),
 ("llm_vs_fallback", "Model vs fallback", "Share of generated rows that came from the language model versus deterministic fallback.", "Counts of plans and rows by source.", "generation_runs", "Higher model share means more variation.", "Shows resilience and provenance.", "Warm-up weeks use fallback.", "trust"),
 ("beat_viewer", "Story beats", "Scripted events that are guaranteed to exist and be detected.", "Ten beats with effect sizes enforced by the engine and detectors checked.", "scenario", "Each shows whether its detector fired.", "Ensures the demo story is real.", "Dates are relative to the start.", "trust"),
 ("cost_ledger", "Cost ledger", "Model usage by role, model and day.", "Tokens aggregated from every call; dollars shown only if prices are set.", "llm_calls", "Cached calls cost nothing.", "Keeps spend visible.", "Prices are not assumed.", "trust"),
 ("glossary", "Glossary", "Searchable definitions of terms used in the app.", "Generated from the tooltip file.", "tooltips", "Search by word.", "Shared language.", "Synthetic data.", "trust"),
 ("methodology", "Methodology", "How the numbers are produced and what is simulated.", "Deterministic simulation guided by language-model plans, validated by code.", "design", "Read the simulated-ness list.", "Honest about limits.", "Not official.", "trust"),
]
RULES = {
 "R-SLA-01": ("SLA breach alert", "Raised when more than 15% of an agency's records for a stage breach the service level in 24 hours.", "Breach rate over records in the window; needs at least 40 records.", "stage_events", "Open the alert to see the stage and the records.", "Agency timeliness is a core supervision metric.", "SLA hours are simulated.", "supervision"),
 "R-PHYS-01": ("Physical bottleneck alert", "Raised when the median examination wait at a port exceeds 1.8 times its recent baseline.", "Median planned exam wait over six hours versus the previous 14 days at the same port.", "stage_events", "A ratio of 2.5 means waits are 2.5 times normal.", "Physical delays are outside the platform's control.", "Uses queue-entry wait estimates.", "speed"),
 "R-FEE-01": ("Fee shortfall alert", "Raised when a commodity and origin pair is assessed more than 8% below the fee-rule expectation over three days.", "Expected minus assessed divided by expected, for at least 20 assessments.", "fee_assessments", "Open the heatmap to see the pair.", "Revenue assurance.", "Expected amounts are simulated.", "trust"),
 "R-REC-01": ("Paid-not-settled alert", "Raised when 30 or more payments at a bank are older than 48 hours and unsettled.", "Count of unsettled payments older than T+2 per bank.", "payment_allocations", "Check the bank's settlement lag.", "Money is stuck in the rail.", "Timing items under 48 hours are ignored.", "trust"),
 "R-SET-01": ("Settlement lag alert", "Raised when a bank's settlement batch takes more than 48 hours.", "Completed minus closed time, or age of an open batch.", "settlement_batches", "T+3 means 72 hours.", "Slow banks hold agency cash.", "Simulated lags.", "supervision"),
 "R-REM-01": ("Late remittance alert", "Raised when an agency pays its share to the Treasury more than 3 days after the due date.", "Paid minus due date; unpaid items are measured to now.", "remittances", "High severity means the delay exceeds the threshold.", "Timely remittance protects government cash flow.", "Remittance rules are simulated.", "supervision"),
 "R-DUP-01": ("Duplicate payments alert", "Raised when five or more duplicate payments arrive within an hour.", "Count of duplicate-flagged payments in 60 minutes.", "payments", "Bursts usually come from one channel.", "Protects traders and reconciliation.", "Synthetic.", "trust"),
 "R-FX-01": ("FX move alert", "Raised when USD/NGN moves more than 2% in a day.", "Daily rate divided by the previous day's rate minus one.", "fx_rates", "Info severity: context for fee changes.", "Explains swings in naira collections.", "Simulated path.", "trust"),
 "R-DQ-01": ("Data completeness alert", "Raised when an agency's record completeness falls below 90% in 24 hours.", "Share of stage records with all fields; at least 40 records.", "stage_events", "Open the alert to see incomplete records.", "Data quality limits trust.", "Synthetic gaps.", "trust"),
 "R-CASH-01": ("Collection cost spike alert", "Raised when an agency's collection cost ratio exceeds 1.5 times its 30-day mean.", "Seven-day ratio divided by 30-day ratio.", "settlements", "Rare in this simulation.", "Cost control.", "Simulated rates.", "trust"),
 "R-TGT-01": ("Target projection alert", "Raised when the dwell trend is projected to miss the end-2026 target.", "Trend projection of weekly median dwell.", "consignments", "Info severity.", "Early view of programme risk.", "Linear projection.", "speed"),
 "R-ONB-01": ("Onboarding lag alert", "Raised when under 80% of an agency's records arrive digitally in 24 hours.", "Share of records captured digitally.", "stage_events", "Improves as onboarding progresses.", "Tracks adoption.", "Simulated trajectory.", "supervision"),
}


def build() -> dict:
    out = {}
    for key, label, short, calc, src, read, why, cav, needs in S:
        out[key] = _entry(label, short, short, calc, src, read, why, cav, needs)
    for code, (label, short, calc, src, read, why, cav, needs) in RULES.items():
        out[code] = _entry(label, short, short, calc, src, read, why, cav, needs)
    return out


def _entry(label, short, what, calc, src, read, why, cav, needs) -> dict:
    long = (f"**What it is.** {what}\n**How it is calculated.** {calc}\n**Where it comes from.** `{src}`.\n**How to read it.** {read}\n"
            f"**Why the NSW cares.** {why}\n**Caveats.** {cav}")
    return {"label": label, "short": short, "long": long, "needs": [n.strip() for n in needs.split(",")], "sources": [s.strip(" `") for s in src.split(",")]}


if __name__ == "__main__":
    data = build()
    (ROOT / "config" / "tooltips.yaml").write_text(yaml.safe_dump(data, sort_keys=True, allow_unicode=True, width=1000), encoding="utf-8")
    print(f"wrote {len(data)} tooltip entries")
